ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_OUT_FOR_DELIVERY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_DELIVERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_CANCELLED';
